/* Writes public/sitemap.xml (and public/robots.txt's companion) from the
   route list in src/config/seo.js — one source of truth, so a new page
   cannot ship with metadata but no sitemap entry.

   Wired into `npm run build`, so every deploy publishes a sitemap whose
   <lastmod> matches the build. Run it on its own with:

     node scripts/generateSitemap.js

   Submit https://tekniik.ai/sitemap.xml once in Google Search Console;
   robots.txt points at it too, so other crawlers find it unaided. */

import { writeFileSync, mkdirSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { ROUTES, ORIGIN, canonicalFor } from '../src/config/seo.js'

const here = dirname(fileURLToPath(import.meta.url))
const out = resolve(here, '..', 'public', 'sitemap.xml')

const lastmod = new Date().toISOString().slice(0, 10)

/* Crawl priority is a hint only, but it costs nothing to rank our own
   pages honestly: home first, the money pages next, legal last. */
function weightFor(route) {
  if (route === '/') return { priority: '1.0', changefreq: 'weekly' }
  if (route === '/website-plans') return { priority: '0.9', changefreq: 'weekly' }
  if (route.startsWith('/services')) return { priority: '0.9', changefreq: 'monthly' }
  if (route === '/work' || route.startsWith('/case/')) {
    return { priority: '0.8', changefreq: 'monthly' }
  }
  if (route === '/contact' || route === '/about' || route === '/support') {
    return { priority: '0.7', changefreq: 'monthly' }
  }
  return { priority: '0.3', changefreq: 'yearly' }
}

const urls = ROUTES.map((route) => {
  const { priority, changefreq } = weightFor(route)
  return [
    '  <url>',
    `    <loc>${canonicalFor(route)}</loc>`,
    `    <lastmod>${lastmod}</lastmod>`,
    `    <changefreq>${changefreq}</changefreq>`,
    `    <priority>${priority}</priority>`,
    '  </url>',
  ].join('\n')
}).join('\n')

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generateSitemap.js from src/config/seo.js.
     Do not hand-edit: add the route in seo.js and rebuild. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>
`

mkdirSync(dirname(out), { recursive: true })
writeFileSync(out, xml, 'utf8')

console.log(`sitemap: ${ROUTES.length} URLs → public/sitemap.xml (${ORIGIN}, lastmod ${lastmod})`)
